### ISSUE TITLE
Pinnacle Sports API

### ISSUE THREAD

**Issue by shtefcs** [Kalagan/pinnacle-sports#5]
Honestly, its easier to me to ask here, cause you probably already know.

Is **Pinnacle Sports API** free ?

I did quick check, but didn't find pricing .

Also, do you have example app you created using their API ?

Peace

**Comment by JulienSansot** [comment]
To use the API you need to have a Pinnacle Sports account with some money in it.
You should try first to use the Pinnacle Sports website before using this node module.
I don't have an example app that I can share with you sorry.
There is a simple example at the bottom of the README https://github.com/Kalagan/pinnacle-sports

Peace to you

**Comment by shtefcs** [comment]
If I am getting right, you are talking about betting via API ? What if you want to get just stats of matches ?

I am looking to find javascript API or app which can get live results of sport matches. Is this can be used for ?

**Comment by JulienSansot** [comment]
Well, in the manual (http://www.pinnaclesports.com/en/api/manual) in the **Overview** section it says :
_Please note that in order to access Pinnacle Sports API you must have a funded account._
So I think you can use this API for free to get the match results but you need to put a bit of money in your PinnacleSports account.
And I'm not sure if you can get the "live" results. Maybe the results are updated only when the game is finished.

**Comment by shtefcs** [comment]
Ok Kalagan. Thank you for your time!

**Comment by JulienSansot** [comment]
No problems
